M48
; DRILL file {KiCad 9.0.4} date 2025-09-01T18:40:25-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-01T18:40:25-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X24.0Y-86.3
T2
X24.0Y-81.8
T3
X9.84Y-5.16
X21.27Y-5.16
X26.74Y-5.16
X38.17Y-5.16
M30
