/* =========================================================================
 * cdi_validator.js  —  OpenLCB CDI XML validator
 *
 * Exposes: window.CdiValidator.validate(xmlString)
 *
 * Returns: Promise<Array of
 *   { severity: 'error'|'warning'|'info', message: string, line: number|null }>
 *
 * Layer 1+2 — Well-formedness + Structural rules :
 *     Handled by xmllint (patched libxml2 compiled to asm.js via Emscripten)
 *     validating against the CDI 1.4 XSD.
 *     Async — each call creates a fresh Emscripten module instance.
 *     Gives accurate line numbers from patched libxml2.
 *
 * Layer 3 — Semantic hints :
 *     Custom checks for domain-specific best practices that the XSD
 *     cannot express (missing ACDI, space 253, min>max, etc.)
 * ========================================================================= */

(function () {

    /* -------------------------------------------------------------------
     * Embedded CDI XSD — regenerated by update_xsd.py
     * ------------------------------------------------------------------- */
    /* <<CDI_XSD_START>> */
    var _xsdText = '<?xml version="1.0" encoding="utf-8"?>\n<?xml-stylesheet href="schema2xhtml.xsl" type="text/xsl"?>\n<!-- XML Schema for OpenLCB Configuration Description Information (CDI)     -->\n<xs:schema version="CDI 1.4" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\n\n  <xs:complexType name="mapType">\n    <xs:annotation>\n      <xs:documentation>\n        A map relates one or more property elements (keys)\n        to specific values.\n      </xs:documentation>\n    </xs:annotation>\n    <xs:sequence>\n      <xs:element name="name" minOccurs="0" maxOccurs="1" />\n      <xs:element name="description" minOccurs="0" maxOccurs="1" />\n      <xs:element name="relation" minOccurs="0" maxOccurs="unbounded">\n        <xs:complexType>\n          <xs:sequence>\n            <xs:element name="property" minOccurs="1" maxOccurs="1" />\n            <xs:element name="value" minOccurs="1" maxOccurs="1" />\n          </xs:sequence>\n        </xs:complexType>\n      </xs:element>\n    </xs:sequence>\n  </xs:complexType>\n\n  <xs:simpleType name="booleanType">\n    <xs:annotation>\n        <xs:documentation>\n          General definition for a string that represents a boolean\n          via yes/true/1 and no/false/0 values\n        </xs:documentation>\n    </xs:annotation>\n    <xs:restriction base="xs:token">\n      <xs:enumeration value="yes"/>\n      <xs:enumeration value="no"/>\n      <xs:enumeration value="true"/>\n      <xs:enumeration value="false"/>\n      <xs:enumeration value="1"/>\n      <xs:enumeration value="0"/>\n    </xs:restriction>\n  </xs:simpleType>\n\n  <xs:complexType name="groupHintsType">\n    <xs:annotation>\n      <xs:documentation>\n        Presents optional hints to a GUI program\n        for how to render the contents of this group.\n      </xs:documentation>\n    </xs:annotation>\n    <xs:sequence>\n      <xs:element name="visibility" minOccurs="0" maxOccurs="1" >\n        <xs:complexType>\n          <xs:attribute name="hideable" type="booleanType" default="no">\n            <xs:annotation>\n              <xs:documentation>\n                Recommends that the group be \n                presented in a form that can be made visible\n                or hidden at the user\'s request.\n              </xs:documentation>\n            </xs:annotation>\n          </xs:attribute>\n          <xs:attribute name="hidden" type="booleanType" default="no">\n            <xs:annotation>\n              <xs:documentation>\n                If yes, recommends a hideable=true group \n                be hidden when first displayed\n              </xs:documentation>\n            </xs:annotation>\n          </xs:attribute>\n       </xs:complexType>\n      </xs:element> \n      <xs:element name="readOnly" minOccurs="0" maxOccurs="1" />\n    </xs:sequence>\n  </xs:complexType>\n\n  <xs:complexType name="groupType">\n    <xs:sequence>\n      <xs:element name="name" minOccurs="0" maxOccurs="1" />\n      <xs:element name="description" minOccurs="0" maxOccurs="1" />\n      <xs:element name="link" type="linkType" minOccurs="0" maxOccurs="1" />\n      <xs:element name="repname" minOccurs="0" maxOccurs="unbounded" />\n      <xs:element name="hints" type="groupHintsType" minOccurs="0" maxOccurs="1" />     \n      <xs:choice minOccurs="0" maxOccurs="unbounded">\n        <xs:annotation>\n          <xs:documentation>\n            Allows any sequence of the contained element types\n          </xs:documentation>\n        </xs:annotation>\n        <xs:element name="group" type="groupType" minOccurs="0" maxOccurs="1" />\n        <xs:element name="string" type="stringType" minOccurs="0" maxOccurs="1" />\n        <xs:element name="int" type="intType" minOccurs="0" maxOccurs="1" />\n        <xs:element name="eventid" type="eventidType" minOccurs="0" maxOccurs="1" />\n        <xs:element name="float" type="floatType" minOccurs="0" maxOccurs="1" />\n        <xs:element name="action" type="actionButtonType" minOccurs="0" maxOccurs="1" />\n        <xs:element name="blob" type="blobType" minOccurs="0" maxOccurs="1" />\n      </xs:choice>\n    </xs:sequence>\n    <xs:attribute name="offset" type="xs:int" default="0">\n      <xs:annotation>\n        <xs:documentation>\n          Positive or negative offset between the address of\n          the end of previous element and the start of\n          this group\'s contents.\n          Offset of zero means that this element starts\n          immediately after the previous one.\n        </xs:documentation>\n      </xs:annotation>\n    </xs:attribute>\n    <xs:attribute name="replication" type="xs:int" default="1" />\n  </xs:complexType>\n\n  <xs:complexType name="eventidType">\n    <xs:sequence>\n      <xs:element name="name" minOccurs="0" maxOccurs="1" />\n      <xs:element name="description" minOccurs="0" maxOccurs="1" />\n      <xs:element name="map" type="mapType" minOccurs="0" maxOccurs="1" />\n    </xs:sequence>\n    <xs:attribute name="offset" type="xs:int" default="0">\n      <xs:annotation>\n        <xs:documentation>\n          Positive or negative offset between the address of\n          the end of previous element and the start of\n          this elements\'s contents.\n          Offset of zero means that this element starts\n          immediately after the previous one.\n        </xs:documentation>\n      </xs:annotation>\n    </xs:attribute>\n  </xs:complexType>\n\n  <xs:complexType name="integerHintsType">\n    <xs:annotation>\n      <xs:documentation>\n        Presents optional hints to a GUI program\n        for how to render this integer variable.\n      </xs:documentation>\n    </xs:annotation>\n    <xs:sequence>\n      <xs:element name="slider" minOccurs="0" maxOccurs="1" >\n        <xs:complexType>\n          <xs:attribute name="tickSpacing" type="xs:integer" default="0">\n            <xs:annotation>\n              <xs:documentation>\n                Recommends a value for the spacing between \n                tick marks on the slider.  For example, "10" with a \n                minimum value of 0 would recommend ticks at 0, 10, 20 etc\n                along the slider axis. Values of zero or less\n                recommend that no tick marks be displayed.\n              </xs:documentation>\n            </xs:annotation>\n          </xs:attribute>\n          <xs:attribute name="immediate" type="booleanType" default="no">\n            <xs:annotation>\n              <xs:documentation>\n                If yes, recommends that the slider should write to the \n                configuration memory immediately when changed\n              </xs:documentation>\n            </xs:annotation>\n          </xs:attribute>\n          <xs:attribute name="showValue" type="booleanType" default="no">\n            <xs:annotation>\n              <xs:documentation>\n                If yes, recommends that a slider should also \n                show the exact value, perhaps in a near-by numeric field\n              </xs:documentation>\n            </xs:annotation>\n          </xs:attribute>\n        </xs:complexType>\n      </xs:element> \n      <xs:element name="radiobutton" minOccurs="0" maxOccurs="1" />\n      <xs:element name="checkbox" minOccurs="0" maxOccurs="1" />\n    </xs:sequence>\n  </xs:complexType>\n  \n  <xs:complexType name="intType">\n    <xs:sequence>\n      <xs:element name="name" minOccurs="0" maxOccurs="1" />\n      <xs:element name="description" minOccurs="0" maxOccurs="1" />\n      <xs:element name="min" minOccurs="0" maxOccurs="1" />\n      <xs:element name="max" minOccurs="0" maxOccurs="1" />\n      <xs:element name="default" minOccurs="0" maxOccurs="1" />\n      <xs:element name="map" type="mapType" minOccurs="0" maxOccurs="1">\n        <xs:annotation>\n          <xs:documentation>\n            The \'value\' of each entry is displayed, and\n            the \'property\' content (number) is sent\n            to/from the node\n          </xs:documentation>\n        </xs:annotation>\n      </xs:element>\n      <xs:element name="hints" type="integerHintsType" minOccurs="0" maxOccurs="1" />     \n    </xs:sequence>\n    <xs:attribute name="size" default="1">\n      <xs:annotation>\n        <xs:documentation>\n          Storage size of this variable in bytes.\n        </xs:documentation>\n      </xs:annotation>\n      <xs:simpleType>\n        <xs:restriction base="xs:token">\n          <xs:enumeration value="1"/>\n          <xs:enumeration value="2"/>\n          <xs:enumeration value="4"/>\n          <xs:enumeration value="8"/>\n        </xs:restriction>\n      </xs:simpleType>\n    </xs:attribute>\n    <xs:attribute name="offset" type="xs:int" default="0">\n      <xs:annotation>\n        <xs:documentation>\n          Positive or negative offset between the\n          address of the end of previous element and the\n          start of this elements\'s contents.\n          Offset of zero means that this element starts\n          immediately after the previous one.\n        </xs:documentation>\n      </xs:annotation>\n    </xs:attribute>\n  </xs:complexType>\n\n  <xs:simpleType name="floatFormat">\n	<xs:restriction base="xs:string">\n	  <!-- This is a somewhat limiting regex, as it does not allow all possible -->\n	  <!-- printf formats.   It will allow the most common formats that I have -->\n	  <!-- seen and used before, howerver -->\n	  <xs:pattern value="%[0-9]*(\\.([0-9]*))?f"/>\n	</xs:restriction>\n  </xs:simpleType>\n\n  <xs:complexType name="floatType">\n	 <xs:sequence>\n      <xs:element name="name" minOccurs="0" maxOccurs="1" />\n      <xs:element name="description" minOccurs="0" maxOccurs="1" />\n      <xs:element name="min" minOccurs="0" maxOccurs="1" />\n      <xs:element name="max" minOccurs="0" maxOccurs="1" />\n      <xs:element name="default" minOccurs="0" maxOccurs="1" />\n      <xs:element name="map" type="mapType" minOccurs="0" maxOccurs="1">\n        <xs:annotation>\n          <xs:documentation>\n            The \'value\' of each entry is displayed, and\n            the \'property\' content (number) is sent\n            to/from the node\n          </xs:documentation>\n        </xs:annotation>\n      </xs:element>\n    </xs:sequence>\n    <xs:attribute name="size" use="required">\n      <xs:annotation>\n        <xs:documentation>\n          Storage size of this variable in bytes. 2, 4 and 8 are valid.\n        </xs:documentation>\n      </xs:annotation>\n      <xs:simpleType>\n        <xs:restriction base="xs:token">\n          <xs:enumeration value="2"/>\n          <xs:enumeration value="4"/>\n          <xs:enumeration value="8"/>\n        </xs:restriction>\n      </xs:simpleType>\n    </xs:attribute>\n    <xs:attribute name="offset" type="xs:int" default="0">\n      <xs:annotation>\n        <xs:documentation>\n          Positive or negative offset between the\n          address of the end of previous element and the\n          start of this elements\'s contents.\n          Offset of zero means that this element starts\n          immediately after the previous one.\n        </xs:documentation>\n      </xs:annotation>\n    </xs:attribute>\n	<xs:attribute name="formatting" type="floatFormat" >\n	      <xs:annotation>\n        <xs:documentation>\n          printf-style format string for displaying data to the user, like %3.1f\n        </xs:documentation>\n      </xs:annotation>\n	</xs:attribute>\n  </xs:complexType>\n\n  <xs:complexType name="stringType">\n    <xs:sequence>\n      <xs:element name="name" minOccurs="0" maxOccurs="1" />\n      <xs:element name="description" minOccurs="0" maxOccurs="1" />\n      <xs:element name="map" type="mapType" minOccurs="0" maxOccurs="1" />\n    </xs:sequence>\n    <xs:attribute name="size" type="xs:int" use="required">\n      <xs:annotation>\n        <xs:documentation>\n          Storage size of this variable in bytes.\n          This includes the trailing null byte that\n          terminates the string content.\n        </xs:documentation>\n      </xs:annotation>\n    </xs:attribute>\n    <xs:attribute name="offset" type="xs:int" default="0">\n      <xs:annotation>\n        <xs:documentation>\n          Positive or negative offset between the\n          address of the end of previous element and the\n          start of this elements\'s contents.\n          Offset of zero means that this element starts\n          immediately after the previous one.\n        </xs:documentation>\n      </xs:annotation>\n    </xs:attribute>\n  </xs:complexType>\n\n  <xs:complexType name="actionButtonType">\n    <xs:sequence>\n      <xs:element name="name" minOccurs="0" maxOccurs="1" />\n      <xs:element name="description" minOccurs="0" maxOccurs="1" />\n      <xs:element name="buttonText" minOccurs="0" maxOccurs="1">\n        <xs:annotation>\n          <xs:documentation>\n            Text to be displayed on the button. \n            This is required.\n          </xs:documentation>\n        </xs:annotation>\n      </xs:element>\n      <xs:element name="dialogText" minOccurs="0" maxOccurs="1">\n        <xs:annotation>\n          <xs:documentation>\n            Text to be displayed on the confirmation dialog. \n            If empty or not present, no confirmation dialog is displayed.\n          </xs:documentation>\n        </xs:annotation>\n      </xs:element>\n      <xs:element name="value" minOccurs="1" maxOccurs="1">\n        <xs:annotation>\n          <xs:documentation>\n            Value to be written when the button is triggered. \n            This is required.\n          </xs:documentation>\n        </xs:annotation>\n      </xs:element>\n    </xs:sequence>\n    <xs:attribute name="size" use="required">\n      <xs:annotation>\n        <xs:documentation>\n          Storage size of this variable in bytes. \n          This is required for backwards compatibility.\n        </xs:documentation>\n      </xs:annotation>\n      <xs:simpleType>\n        <xs:restriction base="xs:token">\n          <xs:enumeration value="1"/>\n          <xs:enumeration value="2"/>\n          <xs:enumeration value="4"/>\n          <xs:enumeration value="8"/>\n        </xs:restriction>\n      </xs:simpleType>\n    </xs:attribute>\n    <xs:attribute name="offset" type="xs:int" default="0">\n      <xs:annotation>\n        <xs:documentation>\n          Positive or negative offset between the address of\n          the end of previous element and the start of\n          this elements\'s contents.\n          Offset of zero means that this element starts\n          immediately after the previous one.\n        </xs:documentation>\n      </xs:annotation>\n    </xs:attribute>\n  </xs:complexType>\n\n  <xs:complexType name="blobType">\n    <xs:sequence>\n      <xs:element name="name" minOccurs="0" maxOccurs="1" />\n      <xs:element name="description" minOccurs="0" maxOccurs="1" />\n    </xs:sequence>\n    <xs:attribute name="size" use="required">\n      <xs:annotation>\n        <xs:documentation>\n          Storage size of this variable in bytes.\n          This is fixed at 10 bytes.\n          An explicit value is required for backwards compatibility.\n        </xs:documentation>\n      </xs:annotation>\n      <xs:simpleType>\n        <xs:restriction base="xs:token">\n          <xs:enumeration value="10"/>\n        </xs:restriction>\n      </xs:simpleType>\n    </xs:attribute>\n    <xs:attribute name="offset" type="xs:int" default="0">\n      <xs:annotation>\n        <xs:documentation>\n          Positive or negative offset between the address of\n          the end of previous element and the start of\n          this elements\'s contents.\n          Offset of zero means that this element starts\n          immediately after the previous one.\n        </xs:documentation>\n      </xs:annotation>\n    </xs:attribute>\n    <xs:attribute name="mode" use="required">\n      <xs:annotation>\n        <xs:documentation>\n          Whether the underlying blob can be read ("read"), can be written ("write"),\n          or both ("readwrite").\n        </xs:documentation>\n      </xs:annotation>\n      <xs:simpleType>\n        <xs:restriction base="xs:token">\n          <xs:enumeration value="read"/>\n          <xs:enumeration value="write"/>\n          <xs:enumeration value="readwrite"/>\n        </xs:restriction>\n      </xs:simpleType>\n    </xs:attribute>\n  </xs:complexType>\n\n  <xs:complexType name="linkType">\n        <xs:simpleContent>\n            <xs:extension base="xs:string">\n                <xs:attribute name="ref" type="xs:string" use="required">\n                  <xs:annotation>\n                    <xs:documentation>\n                      URL for this link.  When the link is triggered\n                      in a configuration tool, it\'s recommended that this\n                      link be retrieved and displayed.\n                    </xs:documentation>\n                  </xs:annotation>\n                </xs:attribute>\n            </xs:extension>\n        </xs:simpleContent>\n  </xs:complexType>\n\n  <!-- Definition of the primary "cdi" element -->\n  <xs:element name="cdi">\n    <xs:annotation>\n      <xs:documentation>\n        This is the schema for Configuration\n        Description Information (cdi)\n      </xs:documentation>\n    </xs:annotation>\n    <xs:complexType>\n      <xs:sequence>\n        <xs:element name="identification" minOccurs="0" maxOccurs="1">\n          <xs:annotation>\n            <xs:documentation>\n              Common first element to identify the decoder\n            </xs:documentation>\n          </xs:annotation>\n          <xs:complexType>\n            <xs:sequence>\n              <xs:element name="manufacturer" minOccurs="0" maxOccurs="1" />\n              <xs:element name="model" minOccurs="0" maxOccurs="1" />\n              <xs:element name="hardwareVersion" minOccurs="0" maxOccurs="1" />\n              <xs:element name="softwareVersion" minOccurs="0" maxOccurs="1" />\n              <xs:element name="link" type="linkType" minOccurs="0" maxOccurs="1" />\n              <xs:element name="map" type="mapType" minOccurs="0" maxOccurs="1">\n                <xs:annotation>\n                  <xs:documentation>\n                    This map can be used to add arbitrary key/value\n                    descriptions of the node.\n                  </xs:documentation>\n                </xs:annotation>\n              </xs:element>\n            </xs:sequence>\n          </xs:complexType>\n        </xs:element>\n        <xs:element name="acdi" minOccurs="0" maxOccurs="1">\n          <xs:annotation>\n            <xs:documentation>\n              Element that identifies that memory information is available\n              as defined by the Abbreviated Common Description Information\n              (ACDI) standard.\n            </xs:documentation>\n          </xs:annotation>\n          <xs:complexType>\n            <xs:attribute name="fixed" type="xs:int" default="4">\n              <xs:annotation>\n                <xs:documentation>\n                  The decimal version number of the format for the fixed\n                  information block.\n                </xs:documentation>\n              </xs:annotation>\n            </xs:attribute>\n            <xs:attribute name="var" type="xs:int" default="2">\n              <xs:annotation>\n                <xs:documentation>\n                  The decimal version number of the format for\n                  the variable information block.\n                </xs:documentation>\n              </xs:annotation>\n            </xs:attribute>\n          </xs:complexType>\n        </xs:element>\n        <xs:element name="segment" minOccurs="0" maxOccurs="unbounded">\n          <xs:annotation>\n            <xs:documentation>\n              Define the contents of a memory space\n            </xs:documentation>\n          </xs:annotation>\n          <xs:complexType>\n            <xs:sequence>\n              <xs:element name="name" minOccurs="0" maxOccurs="1" />\n              <xs:element name="description" minOccurs="0" maxOccurs="1" />\n              <xs:element name="link" type="linkType" minOccurs="0" maxOccurs="1" />\n              <xs:choice minOccurs="0" maxOccurs="unbounded">\n                <xs:annotation>\n                  <xs:documentation>\n                    Allows any sequence of the contained element types\n                  </xs:documentation>\n                </xs:annotation>\n                <xs:element name="group" type="groupType" minOccurs="0" maxOccurs="1">\n                  <xs:annotation>\n                    <xs:documentation>\n                      Allows grouping and replication of multiple locations.\n                    </xs:documentation>\n                  </xs:annotation>\n                </xs:element>\n                <xs:element name="string" type="stringType" minOccurs="0" maxOccurs="1">\n                  <xs:annotation>\n                    <xs:documentation>\n                      Describes a human-readable UTF-8 string in the data.\n                    </xs:documentation>\n                  </xs:annotation>\n                </xs:element>\n                <xs:element name="int" type="intType" minOccurs="0" maxOccurs="1">\n                  <xs:annotation>\n                    <xs:documentation>\n                      Describes an integer value in the data.\n                      The field can be considered either a number,\n                      or a set of specific coded values via a map.\n                    </xs:documentation>\n                  </xs:annotation>\n                </xs:element>\n                <xs:element name="eventid" type="eventidType" minOccurs="0" maxOccurs="1">\n                  <xs:annotation>\n                    <xs:documentation>\n                      Describes an 8-byte Event ID in the data.\n                    </xs:documentation>\n                  </xs:annotation>\n                </xs:element>\n				<xs:element name="float" type="floatType" minOccurs="0" maxOccurs="1">\n				  <xs:annotation>\n                    <xs:documentation>\n                      Describes a float type in the data\n                    </xs:documentation>\n                  </xs:annotation>\n				</xs:element>\n				<xs:element name="action" type="actionButtonType" minOccurs="0" maxOccurs="1">\n				  <xs:annotation>\n                    <xs:documentation>\n                      Describes how to create an action button to write into the data.\n                    </xs:documentation>\n                  </xs:annotation>\n				</xs:element>\n				<xs:element name="blob" type="blobType" minOccurs="0" maxOccurs="1">\n				  <xs:annotation>\n                    <xs:documentation>\n                      Describes a blob of data that can be read/written/both.\n                    </xs:documentation>\n                  </xs:annotation>\n				</xs:element>\n\n<!--\n                XML Schema 1.1 construct expressing extensibility promise\n                <xs:any minOccurs="0" maxOccurs="1" processContents="lax">\n                <xs:assert test="every $x in * satisfies\n                                    (exists($x/@size) and $x/@size castable to xs:integer)"/>\n                <xs:assert test="every $x in * satisfies\n                                    (exists($x/@offset) and $x/@offset castable to xs:integer)"/>\n                  <xs:annotation>\n                    <xs:documentation>\n                      Extension point for future schema\n                    </xs:documentation>\n                  </xs:annotation>\n                </xs:any>\n -->\n\n              </xs:choice>\n            </xs:sequence>\n            <xs:attribute name="space" type="xs:int" use="required">\n              <xs:annotation>\n                <xs:documentation>\n                  The decimal number of the address space where the information is found.\n                </xs:documentation>\n              </xs:annotation>\n            </xs:attribute>\n            <xs:attribute name="origin" type="xs:int" default="0">\n              <xs:annotation>\n                <xs:documentation>\n                  Starting address of the segment\'s contents\n                  within the memory space.\n                </xs:documentation>\n              </xs:annotation>\n            </xs:attribute>\n          </xs:complexType>\n        </xs:element>\n      </xs:sequence>\n    </xs:complexType>\n  </xs:element>\n</xs:schema>\n';
    /* <<CDI_XSD_END>> */

    /* -------------------------------------------------------------------
     * _parseErrors(errors)  — convert xmllint raw error strings into
     * structured {severity, line, message} objects.
     *
     * Each raw string looks like:
     *   file_0.xml:5: element int: Schemas validity error : ...
     *   file_0.xml:6: parser error : ...
     * ------------------------------------------------------------------- */
    function _parseErrors(errors) {

        if (!errors) { return []; }

        var issues = [];
        var i, raw, parts, lineNum, msg;

        for (i = 0; i < errors.length; i++) {
            raw = errors[i];

            /* Skip the caret-pointer lines ("      ^") and bare XML echo lines */
            if (/^\s*\^/.test(raw))  { continue; }
            if (!/^\/?file_/.test(raw)) { continue; }

            parts   = raw.split(':');
            lineNum = (parts.length >= 2) ? parseInt(parts[1], 10) : null;
            if (isNaN(lineNum)) { lineNum = null; }

            /* Everything after "file_0.xml:<line>:" is the message */
            msg = parts.slice(2).join(':').trim();

            /* Skip summary lines like "file_0.xml fails to validate" */
            if (!msg) { continue; }

            issues.push({
                severity: 'error',
                line:     lineNum,
                col:      null,
                message:  msg
            });
        }

        return issues;
    }

    /* -------------------------------------------------------------------
     * _runSemanticChecks(xmlString)  — Layer 3 domain-specific hints.
     * Uses DOMParser (synchronous).  Only runs when XML is well-formed.
     * Returns an array of {severity, line, col, message}.
     * ------------------------------------------------------------------- */
    function _runSemanticChecks(xmlString) {

        var issues = [];

        var parser = new DOMParser();
        var xmlDoc = parser.parseFromString(xmlString, 'text/xml');

        /* If XML is broken DOMParser inserts <parsererror>.
         * xmllint already reported that, so just bail out here. */
        if (xmlDoc.getElementsByTagName('parsererror').length > 0) {
            return issues;
        }

        var root     = xmlDoc.documentElement;
        var segments = Array.from(root.getElementsByTagName('segment'));

        /* -- identification ------------------------------------------------ */
        var idEl = root.getElementsByTagName('identification')[0];
        if (!idEl) {
            issues.push({ severity: 'warning', line: null, col: null,
                message: 'No <identification> element — manufacturer/model info will be missing from node' });
        } else {
            var mfgEl   = idEl.getElementsByTagName('manufacturer')[0];
            var modelEl = idEl.getElementsByTagName('model')[0];
            if (!mfgEl || !mfgEl.textContent.trim()) {
                issues.push({ severity: 'info', line: null, col: null,
                    message: '<identification> is missing or has an empty <manufacturer>' });
            }
            if (!modelEl || !modelEl.textContent.trim()) {
                issues.push({ severity: 'info', line: null, col: null,
                    message: '<identification> is missing or has an empty <model>' });
            }
        }

        /* -- ACDI ---------------------------------------------------------- */
        if (!root.getElementsByTagName('acdi')[0]) {
            issues.push({ severity: 'info', line: null, col: null,
                message: 'No <acdi/> tag — ACDI protocol will not be advertised by this node' });
        }

        /* -- space 253 (0xFD) — user-accessible name/description ----------- */
        var hasSpace253 = segments.some(function (s) {
            return parseInt(s.getAttribute('space')) === 253;
        });
        if (!hasSpace253) {
            issues.push({ severity: 'info', line: null, col: null,
                message: 'No segment in space 0xFD (253) — user name and description will not be configurable via CDI' });
        }

        /* -- event IDs in space 0xFE (unusual) ----------------------------- */
        segments.filter(function (s) {
            return parseInt(s.getAttribute('space')) === 254;
        }).forEach(function (seg) {
            if (seg.getElementsByTagName('eventid').length > 0) {
                issues.push({ severity: 'info', line: null, col: null,
                    message: 'Event IDs found in space 0xFE (All Memory). This is unusual — event IDs are typically stored in the config space (0xFD).' });
            }
        });

        /* -- space number range 0-255 -------------------------------------- */
        segments.forEach(function (seg, i) {
            var sp = parseInt(seg.getAttribute('space'));
            if (!isNaN(sp) && (sp < 0 || sp > 255)) {
                issues.push({ severity: 'warning', line: null, col: null,
                    message: '<segment> #' + (i + 1) + ' space="' + sp + '" is outside valid range (0-255)' });
            }
        });

        /* -- empty segments ------------------------------------------------ */
        var KNOWN_LEAF_TAGS = new Set(['action', 'blob', 'eventid', 'float', 'int', 'string']);
        segments.forEach(function (seg, i) {
            var hasLeaf = seg.getElementsByTagName('group').length > 0 ||
                          Array.from(seg.children).some(function (c) {
                              return KNOWN_LEAF_TAGS.has(c.tagName);
                          });
            if (!hasLeaf) {
                issues.push({ severity: 'info', line: null, col: null,
                    message: '<segment> #' + (i + 1) + ' (space ' + seg.getAttribute('space') + ') appears to have no configuration items' });
            }
        });

        /* -- min/max consistency on int/float ------------------------------ */
        var numericEls = Array.from(xmlDoc.getElementsByTagName('int'))
            .concat(Array.from(xmlDoc.getElementsByTagName('float')));
        numericEls.forEach(function (el) {
            var minEl = el.getElementsByTagName('min')[0];
            var maxEl = el.getElementsByTagName('max')[0];
            if (minEl && maxEl) {
                var mn = parseFloat(minEl.textContent);
                var mx = parseFloat(maxEl.textContent);
                if (!isNaN(mn) && !isNaN(mx) && mn > mx) {
                    var nameEl = el.getElementsByTagName('name')[0];
                    var n = nameEl ? nameEl.textContent : '(unnamed)';
                    issues.push({ severity: 'warning', line: null, col: null,
                        message: '"' + n + '": <min> (' + mn + ') is greater than <max> (' + mx + ')' });
                }
            }
        });

        /* -- checkbox hint needs exactly 2 map relations ------------------- */
        Array.from(xmlDoc.getElementsByTagName('hints')).forEach(function (hints) {
            var chk = hints.getElementsByTagName('checkbox')[0];
            if (!chk) { return; }
            var parentEl = hints.parentElement;
            var mapEl    = parentEl ? parentEl.getElementsByTagName('map')[0] : null;
            if (!mapEl) {
                issues.push({ severity: 'error', line: null, col: null,
                    message: 'checkbox hint requires a <map> sibling element with exactly 2 relations' });
            } else {
                var rels = mapEl.getElementsByTagName('relation').length;
                if (rels !== 2) {
                    issues.push({ severity: 'error', line: null, col: null,
                        message: 'checkbox hint map has ' + rels + ' relation(s) — exactly 2 required' });
                }
            }
        });

        return issues;
    }

    /* -------------------------------------------------------------------
     * validate(xmlString)  — main entry point.
     * Returns [{severity, line, col, message}, ...]
     *
     * Results are cached so that the two callers (validation panel and
     * CodeMirror linter) do not each re-run xmllint for the same XML.
     * ------------------------------------------------------------------- */
    var _cachedXml    = null;
    var _cachedResult = null;

    function validate(xmlString) {

        /* Return cached result when the XML has not changed */
        if (xmlString === _cachedXml && _cachedResult !== null) {
            return Promise.resolve(_cachedResult);
        }

        /* -- Layer 1+2: xmllint XSD validation (async) --------------------- */
        return xmllint.validateXML({
            xml:    [xmlString],
            schema: [_xsdText]
        }).then(function (result) {

            var issues = _parseErrors(result.errors);

            /* -- Layer 3: semantic hints ----------------------------------- */
            var semanticIssues = _runSemanticChecks(xmlString);
            issues = issues.concat(semanticIssues);

            _cachedXml    = xmlString;
            _cachedResult = issues;

            return issues;
        });
    }

    /* ------------------------------------------------------------------- */
    window.CdiValidator = { validate: validate };

}());
