/* =========================================================================
 * fdi_validator.js  —  OpenLCB FDI XML validator
 *
 * Exposes: window.FdiValidator.validate(xmlString)
 *
 * Returns: Promise<Array of
 *   { severity: 'error'|'warning'|'info', message: string, line: number|null }>
 *
 * Layer 1+2 — Well-formedness + Structural rules :
 *     Handled by xmllint (patched libxml2 compiled to asm.js via Emscripten)
 *     validating against the FDI 1.1 XSD.
 *     Async — each call creates a fresh Emscripten module instance.
 *     Gives accurate line numbers from patched libxml2.
 *
 * Layer 3 — Semantic hints :
 *     Custom checks for domain-specific best practices that the XSD
 *     cannot express (duplicate function numbers, DCC range, etc.)
 * ========================================================================= */

(function () {

    /* -------------------------------------------------------------------
     * Embedded FDI XSD — regenerated by update_xsd.py
     * ------------------------------------------------------------------- */
    /* <<FDI_XSD_START>> */
    var _xsdText = '<?xml version="1.0" encoding="utf-8"?>\n<?xml-stylesheet href="schema2xhtml.xsl" type="text/xsl"?>\n<!-- XML Schema for OpenLCB Function Description Information (FDI)     -->\n<xs:schema version="FDI 1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">\n\n  <xs:simpleType name="FunctionNumberType">\n    <xs:restriction base="xs:int">\n      <xs:minInclusive value="0"/>\n      <xs:maxInclusive value="16777215"/>\n    </xs:restriction>\n  </xs:simpleType>\n\n  <xs:complexType name="groupType">\n    <xs:sequence>\n      <xs:element name="name" minOccurs="0" maxOccurs="1" />\n      <xs:element name="description" minOccurs="0" maxOccurs="1" />\n      <xs:choice minOccurs="0" maxOccurs="unbounded">\n        <xs:annotation>\n          <xs:documentation>\n            Allows any sequence of the contained element types\n          </xs:documentation>\n        </xs:annotation>\n        <xs:element name="group" type="groupType" minOccurs="0" maxOccurs="1" />\n        <xs:element name="function" type="functionType" minOccurs="0" maxOccurs="1" />\n      </xs:choice>\n    </xs:sequence>\n  </xs:complexType>\n\n  <xs:complexType name="functionType">\n    <xs:sequence>\n      <xs:element name="name" minOccurs="0" maxOccurs="1" />\n      <xs:element name="number" type="FunctionNumberType" minOccurs="1" maxOccurs="1" />\n      <xs:element name="min" type="xs:int" minOccurs="0" maxOccurs="1" >\n        <xs:annotation>\n          <xs:documentation>\n            Smallest valid value for this function.\n            Only used when type is "analog".\n            Default is 0.\n          </xs:documentation>\n        </xs:annotation>\n      </xs:element>\n      <xs:element name="max" type="xs:int" minOccurs="0" maxOccurs="1" >\n        <xs:annotation>\n          <xs:documentation>\n            Largest valid value for this function.\n            Only used when type is "analog".\n            Default is 255.\n          </xs:documentation>\n        </xs:annotation>\n      </xs:element>\n    </xs:sequence>\n    <xs:attribute name="kind" default="binary">\n      <xs:annotation>\n        <xs:documentation>\n          Type of function being described\n        </xs:documentation>\n      </xs:annotation>\n      <xs:simpleType>\n        <xs:restriction base="xs:token">\n          <xs:enumeration value="binary"/>\n          <xs:enumeration value="momentary"/>\n          <xs:enumeration value="analog"/>\n        </xs:restriction>\n      </xs:simpleType>\n    </xs:attribute>\n    <xs:attribute name="size" default="1">\n      <xs:annotation>\n        <xs:documentation>\n          Storage size of this variable in bytes.\n          Reserved, ignore upon receipt.\n        </xs:documentation>\n      </xs:annotation>\n      <xs:simpleType>\n        <xs:restriction base="xs:token">\n          <xs:enumeration value="1"/>\n        </xs:restriction>\n      </xs:simpleType>\n    </xs:attribute>\n  </xs:complexType>\n\n  <xs:element name="fdi">\n    <xs:annotation>\n      <xs:documentation>\n        This is the schema for Function\n        Description Information (fdi)\n      </xs:documentation>\n    </xs:annotation>\n    <xs:complexType>\n      <xs:sequence>\n        <xs:element name="segment" minOccurs="1" maxOccurs="1">\n          <xs:annotation>\n            <xs:documentation>\n              Define the contents of the function memory space\n            </xs:documentation>\n          </xs:annotation>\n          <xs:complexType>\n            <xs:sequence>\n              <xs:element name="name" minOccurs="0" maxOccurs="1" />\n              <xs:element name="description" minOccurs="0" maxOccurs="1" />\n              <xs:choice minOccurs="0" maxOccurs="unbounded">\n                <xs:annotation>\n                  <xs:documentation>\n                    Allows any sequence of the contained element types\n                  </xs:documentation>\n                </xs:annotation>\n                <xs:element name="group" type="groupType" minOccurs="0" maxOccurs="1">\n                  <xs:annotation>\n                    <xs:documentation>\n                      Allows grouping of multiple functions.\n                    </xs:documentation>\n                  </xs:annotation>\n                </xs:element>\n                <xs:element name="function" type="functionType" minOccurs="0" maxOccurs="1">\n                  <xs:annotation>\n                    <xs:documentation>\n                      Describes one function.\n                    </xs:documentation>\n                  </xs:annotation>\n                </xs:element>\n\n<!--\n                XML Schema 1.1 construct expressing extensibility promise\n                <xs:any minOccurs="0" maxOccurs="1" processContents="lax">\n                <xs:assert test="every $x in * satisfies\n                                    (exists($x/@size) and $x/@size castable to xs:integer)"/>\n                <xs:assert test="every $x in * satisfies\n                                    (exists($x/@offset) and $x/@offset castable to xs:integer)"/>\n                  <xs:annotation>\n                    <xs:documentation>\n                      Extension point for future schema\n                    </xs:documentation>\n                  </xs:annotation>\n                </xs:any>\n -->\n\n              </xs:choice>\n            </xs:sequence>\n            <xs:attribute name="space" default="249">\n              <xs:annotation>\n                <xs:documentation>\n                  The decimal number of the address space where the information is found.\n                  Reserved, ignore upon receipt.\n                </xs:documentation>\n              </xs:annotation>\n              <xs:simpleType>\n                <xs:restriction base="xs:token">\n                  <xs:enumeration value="249"/>\n                </xs:restriction>\n              </xs:simpleType>\n            </xs:attribute>\n            <xs:attribute name="origin" default="0">\n              <xs:annotation>\n                <xs:documentation>\n                  Starting address of the segment\'s contents\n                  within the memory space. \n                  Reserved, ignore upon receipt.\n                </xs:documentation>\n              </xs:annotation>\n              <xs:simpleType>\n                <xs:restriction base="xs:token">\n                  <xs:enumeration value="0"/>\n                </xs:restriction>\n              </xs:simpleType>\n            </xs:attribute>\n          </xs:complexType>\n        </xs:element>\n      </xs:sequence>\n    </xs:complexType>\n  </xs:element>\n</xs:schema>\n';
    /* <<FDI_XSD_END>> */

    /* -------------------------------------------------------------------
     * _parseErrors(errors)  — convert xmllint raw error strings into
     * structured {severity, line, message} objects.
     * ------------------------------------------------------------------- */
    function _parseErrors(errors) {

        if (!errors) { return []; }

        var issues = [];
        var i, raw, parts, lineNum, msg;

        for (i = 0; i < errors.length; i++) {
            raw = errors[i];

            if (/^\s*\^/.test(raw))  { continue; }
            if (!/^\/?file_/.test(raw)) { continue; }

            parts   = raw.split(':');
            lineNum = (parts.length >= 2) ? parseInt(parts[1], 10) : null;
            if (isNaN(lineNum)) { lineNum = null; }

            msg = parts.slice(2).join(':').trim();

            /* Skip summary lines like "file_0.xml fails to validate" */
            if (!msg) { continue; }

            issues.push({
                severity: 'error',
                line:     lineNum,
                col:      null,
                message:  msg
            });
        }

        return issues;
    }

    /* -------------------------------------------------------------------
     * _runSemanticChecks(xmlString)  — Layer 3 domain-specific hints.
     * Uses DOMParser (synchronous).  Only runs when XML is well-formed.
     * Returns an array of {severity, line, col, message}.
     * ------------------------------------------------------------------- */
    function _runSemanticChecks(xmlString) {

        var issues = [];

        var parser = new DOMParser();
        var xmlDoc = parser.parseFromString(xmlString, 'text/xml');

        if (xmlDoc.getElementsByTagName('parsererror').length > 0) {
            return issues;
        }

        var root         = xmlDoc.documentElement;
        var segments     = Array.from(root.getElementsByTagName('segment'));
        var allFunctions = Array.from(xmlDoc.getElementsByTagName('function'));

        /* -- no segments --------------------------------------------------- */
        if (segments.length === 0) {
            issues.push({ severity: 'warning', line: null, col: null,
                message: 'No <segment> element found — FDI needs at least one segment' });
        }

        /* -- segments with no functions ------------------------------------ */
        segments.forEach(function (seg, i) {
            if (seg.getElementsByTagName('function').length === 0) {
                issues.push({ severity: 'info', line: null, col: null,
                    message: '<segment> #' + (i + 1) + ' has no <function> elements' });
            }
        });

        /* -- space should be 249 (0xF9) ------------------------------------ */
        segments.forEach(function (seg, i) {
            var sp = parseInt(seg.getAttribute('space'));
            if (!isNaN(sp) && sp !== 249) {
                issues.push({ severity: 'warning', line: null, col: null,
                    message: '<segment> #' + (i + 1) + ' space="' + sp + '" — FDI should use space 249 (0xF9)' });
            }
        });

        /* -- duplicate function numbers ------------------------------------ */
        var numbersSeen = {};
        allFunctions.forEach(function (fn) {
            var numAttr = fn.getAttribute('number');
            var numEl   = fn.getElementsByTagName('number')[0];
            var numVal  = numAttr !== null ? numAttr : (numEl ? numEl.textContent.trim() : null);
            if (numVal === null || numVal === '') { return; }

            var n = parseInt(numVal);
            if (isNaN(n)) { return; }

            var nameEl = fn.getElementsByTagName('name')[0];
            var label  = nameEl ? nameEl.textContent.trim() : '(unnamed)';

            if (numbersSeen[n]) {
                issues.push({ severity: 'warning', line: null, col: null,
                    message: 'Duplicate function number ' + n + ' on "' + label + '" — also used by "' + numbersSeen[n] + '"' });
            } else {
                numbersSeen[n] = label;
            }
        });

        /* -- function numbers outside standard DCC range ------------------- */
        allFunctions.forEach(function (fn) {
            var numAttr = fn.getAttribute('number');
            var numEl   = fn.getElementsByTagName('number')[0];
            var numVal  = numAttr !== null ? numAttr : (numEl ? numEl.textContent.trim() : null);
            if (numVal === null) { return; }

            var n = parseInt(numVal);
            if (!isNaN(n) && n > 28) {
                var nameEl = fn.getElementsByTagName('name')[0];
                var label  = nameEl ? nameEl.textContent.trim() : '(unnamed)';
                issues.push({ severity: 'info', line: null, col: null,
                    message: '<function> "' + label + '" uses number ' + n + ' — outside standard DCC range (0-28)' });
            }
        });

        return issues;
    }

    /* -------------------------------------------------------------------
     * validate(xmlString)  — main entry point.
     * Returns [{severity, line, col, message}, ...]
     *
     * Results are cached so that the two callers (validation panel and
     * CodeMirror linter) do not each re-run xmllint for the same XML.
     * ------------------------------------------------------------------- */
    var _cachedXml    = null;
    var _cachedResult = null;

    function validate(xmlString) {

        /* Return cached result when the XML has not changed */
        if (xmlString === _cachedXml && _cachedResult !== null) {
            return Promise.resolve(_cachedResult);
        }

        /* -- Layer 1+2: xmllint XSD validation (async) --------------------- */
        return xmllint.validateXML({
            xml:    [xmlString],
            schema: [_xsdText]
        }).then(function (result) {

            var issues = _parseErrors(result.errors);

            /* -- Layer 3: semantic hints ----------------------------------- */
            var semanticIssues = _runSemanticChecks(xmlString);
            issues = issues.concat(semanticIssues);

            _cachedXml    = xmlString;
            _cachedResult = issues;

            return issues;
        });
    }

    /* ------------------------------------------------------------------- */
    window.FdiValidator = { validate: validate };

}());
