/* =========================================================================
 * Driver Code Generator — generates .h and .c stub files
 * from DRIVER_GROUPS definitions and checked function list.
 *
 * When a platformState is provided and the selected platform has templates
 * for the current driver group, the generated .c file uses those templates
 * instead of empty TODO stubs.
 * ========================================================================= */

const DriverCodegen = {

    /* ----- Template parameter substitution ----- */

    _substituteParams: function (text, params) {

        if (!text || !params) { return text; }

        return text.replace(/\{\{(\w+)\}\}/g, function (match, paramId) {

            return (params[paramId] !== undefined) ? params[paramId] : match;

        });

    },

    /* ----- Resolve platform driver data for current group ----- */

    _getPlatformDrivers: function (groupKey, platformState) {

        if (!platformState || !platformState.platform || platformState.platform === 'none') {
            return null;
        }

        if (typeof PLATFORM_DEFS === 'undefined') { return null; }

        var def = PLATFORM_DEFS[platformState.platform];
        if (!def) { return null; }

        if (groupKey === 'can-drivers') { return def.canDrivers || null; }
        if (groupKey === 'olcb-drivers') { return def.olcbDrivers || null; }

        return null;

    },

    /* ----- .h file generation ----- */

    generateH: function (group, checkedFunctions, platformState) {

        var self = this;
        var groupKey = null;

        /* Determine which group key we're generating for */
        Object.keys(DRIVER_GROUPS).forEach(function (key) {
            if (DRIVER_GROUPS[key] === group) { groupKey = key; }
        });

        var platDrivers = self._getPlatformDrivers(groupKey, platformState);
        var params = (platformState && platformState.params) ? platformState.params : {};

        const lines = [];

        lines.push('/**');
        lines.push(' * @file ' + group.filePrefix + '.h');
        lines.push(' * @brief Hardware driver prototypes for ' + group.title + '.');
        lines.push(' *');
        lines.push(' * @copyright');
        lines.push(' *   Copyright (c) <YEAR>, <YOUR NAME OR COMPANY>');
        lines.push(' *   <YOUR LICENSE TEXT HERE>');
        lines.push(' *');
        lines.push(' * Generated by Node Wizard — https://github.com/JimKueneman/OpenLcbCLib');
        lines.push(' */');
        lines.push('');
        lines.push('#ifndef ' + group.headerGuard);
        lines.push('#define ' + group.headerGuard);
        lines.push('');
        lines.push('#include <stdbool.h>');
        lines.push('#include <stdint.h>');
        lines.push('');

        group.includes.forEach(function (inc) {

            lines.push(inc);

        });

        /* Platform-specific extra includes for the header */
        if (platDrivers && platDrivers.extraIncludes) {

            lines.push('');
            platDrivers.extraIncludes.forEach(function (inc) {

                lines.push(self._substituteParams(inc, params));

            });

        }

        lines.push('');
        lines.push('#ifdef __cplusplus');
        lines.push('extern "C"');
        lines.push('{');
        lines.push('#endif /* __cplusplus */');
        lines.push('');

        checkedFunctions.forEach(function (fn) {

            lines.push('    extern ' + fn.returnType + ' ' + group.functionPrefix + '_' + fn.name + '(' + fn.params + ');');
            lines.push('');

        });

        lines.push('#ifdef __cplusplus');
        lines.push('}');
        lines.push('#endif /* __cplusplus */');
        lines.push('');
        lines.push('#endif /* ' + group.headerGuard + ' */');
        lines.push('');

        return lines.join('\n');

    },

    /* ----- .c file generation ----- */

    generateC: function (group, checkedFunctions, platformState, isArduino) {

        var self = this;
        var srcExt = isArduino ? '.cpp' : '.c';
        var groupKey = null;

        Object.keys(DRIVER_GROUPS).forEach(function (key) {
            if (DRIVER_GROUPS[key] === group) { groupKey = key; }
        });

        var platDrivers = self._getPlatformDrivers(groupKey, platformState);
        var params = (platformState && platformState.params) ? platformState.params : {};
        var templates = (platDrivers && platDrivers.templates) ? platDrivers.templates : {};

        const lines = [];

        lines.push('/**');
        lines.push(' * @file ' + group.filePrefix + srcExt);
        lines.push(' * @brief Hardware driver implementations for ' + group.title + '.');
        lines.push(' *        Connect OpenLcbCLib to your CAN controller, timers, and');
        lines.push(' *        platform resources.');
        lines.push(' *');
        lines.push(' * @copyright');
        lines.push(' *   Copyright (c) <YEAR>, <YOUR NAME OR COMPANY>');
        lines.push(' *   <YOUR LICENSE TEXT HERE>');
        lines.push(' *');
        lines.push(' * Generated by Node Wizard — https://github.com/JimKueneman/OpenLcbCLib');
        lines.push(' */');
        lines.push('');
        lines.push('#include "' + group.filePrefix + '.h"');

        /* Platform-specific extra includes for the .c file */
        if (platDrivers && platDrivers.extraIncludes) {

            platDrivers.extraIncludes.forEach(function (inc) {

                lines.push(self._substituteParams(inc, params));

            });

        }

        /* Platform-specific globals (static vars, ISRs, helpers) */
        if (platDrivers && platDrivers.globals) {

            lines.push(self._substituteParams(platDrivers.globals, params));

        }

        checkedFunctions.forEach(function (fn) {

            lines.push('');
            lines.push('');
            lines.push(fn.returnType + ' ' + group.functionPrefix + '_' + fn.name + '(' + fn.params + ') {');
            lines.push('');

            if (templates[fn.name]) {

                lines.push(self._substituteParams(templates[fn.name], params));

            } else {

                lines.push('    // TODO: Implement ' + fn.name);

                if (fn.returnType === 'bool') {

                    lines.push('    return true;');

                } else if (fn.returnType === 'uint16_t') {

                    lines.push('    return 0;');

                } else if (fn.returnType === 'uint8_t') {

                    lines.push('    return 0;');

                } else if (fn.returnType !== 'void') {

                    lines.push('    return 0;');

                }

            }

            lines.push('');
            lines.push('}');

        });

        lines.push('');

        return lines.join('\n');

    }

};
