/* =========================================================================
 * Callback Code Generator — generates .h and .c stub files
 * from CALLBACK_GROUPS definitions and checked function list.
 * ========================================================================= */

const CallbackCodegen = {

    generateH: function (group, checkedFunctions) {

        const lines = [];

        lines.push('/**');
        lines.push(' * @file ' + group.filePrefix + '.h');
        lines.push(' * @brief Application callback prototypes for ' + group.title + '.');
        lines.push(' *');
        lines.push(' * @copyright');
        lines.push(' *   Copyright (c) <YEAR>, <YOUR NAME OR COMPANY>');
        lines.push(' *   <YOUR LICENSE TEXT HERE>');
        lines.push(' *');
        lines.push(' * Generated by Node Wizard — https://github.com/JimKueneman/OpenLcbCLib');
        lines.push(' */');
        lines.push('');
        lines.push('#ifndef ' + group.headerGuard);
        lines.push('#define ' + group.headerGuard);
        lines.push('');
        lines.push('#include <stdbool.h>');
        lines.push('#include <stdint.h>');
        lines.push('');

        group.includes.forEach(function (inc) {

            lines.push(inc);

        });

        lines.push('');
        lines.push('#ifdef __cplusplus');
        lines.push('extern "C"');
        lines.push('{');
        lines.push('#endif /* __cplusplus */');
        lines.push('');

        checkedFunctions.forEach(function (fn) {

            lines.push('    extern ' + fn.returnType + ' ' + group.functionPrefix + '_' + fn.name + '(' + fn.params + ');');
            lines.push('');

        });

        lines.push('#ifdef __cplusplus');
        lines.push('}');
        lines.push('#endif /* __cplusplus */');
        lines.push('');
        lines.push('#endif /* ' + group.headerGuard + ' */');
        lines.push('');

        return lines.join('\n');

    },

    generateC: function (group, checkedFunctions, isArduino) {

        var srcExt = isArduino ? '.cpp' : '.c';
        const lines = [];

        lines.push('/**');
        lines.push(' * @file ' + group.filePrefix + srcExt);
        lines.push(' * @brief Application callback implementations for ' + group.title + '.');
        lines.push(' *        Customize these stubs to add your application logic.');
        lines.push(' *');
        lines.push(' * @copyright');
        lines.push(' *   Copyright (c) <YEAR>, <YOUR NAME OR COMPANY>');
        lines.push(' *   <YOUR LICENSE TEXT HERE>');
        lines.push(' *');
        lines.push(' * Generated by Node Wizard — https://github.com/JimKueneman/OpenLcbCLib');
        lines.push(' */');
        lines.push('');
        lines.push('#include "' + group.filePrefix + '.h"');
        lines.push('');

        checkedFunctions.forEach(function (fn) {

            lines.push('');
            lines.push(fn.returnType + ' ' + group.functionPrefix + '_' + fn.name + '(' + fn.params + ') {');
            lines.push('');
            lines.push('    // TODO: Implement ' + fn.name);

            if (fn.returnType === 'bool') {

                lines.push('    return true;');

            } else if (fn.returnType !== 'void') {

                lines.push('    return 0;');

            }

            lines.push('');
            lines.push('}');

        });

        lines.push('');

        return lines.join('\n');

    }

};
