; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:native]
platform = native


build_flags = -std=gnu99
              -D NATIVE=1
              -lpthread
              -g

build_src_filter = -<**>
                   +<*.c>
                   +<*.cpp>
                   +<*.h>
                   +<openlcb_c_lib/drivers/*.c>
                   +<openlcb_c_lib/drivers/*.h>
                   +<openlcb_c_lib/drivers/canbus/*.c>
                   +<openlcb_c_lib/drivers/canbus/*.h>
                   +<openlcb_c_lib/openlcb/*.c>
                   +<openlcb_c_lib/openlcb/*.h>
                   +<openlcb_c_lib/utilities/*.c>
                   +<openlcb_c_lib/utilities/*.h>
                   +<application_callbacks/*.c>
                   +<application_callbacks/*.h>
                   +<application_drivers/*.c>
                   +<application_drivers/*.cpp>
