#include "cdi_data.h"

const char cdi_xml[] =
    "<?xml version='1.0' encoding='UTF-8'?>"
    "<cdi xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'"
    " xsi:noNamespaceSchemaLocation='https://openlcb.org/schema/cdi/1/1/cdi.xsd'>"

    "<identification>"
    "<manufacturer>Canbus Outpost</manufacturer>"
    "<model>Servo Switch Controller</model>"
    "<hardwareVersion>Rev A</hardwareVersion>"
    "<softwareVersion>1.0</softwareVersion>"
    "</identification>"

    "<segment space='253' origin='0'>"
    "<name>Node Identity</name>"
    "<string size='64'><name>User Name</name></string>"
    "<string size='64'><name>User Description</name></string>"
    "</segment>"

    "<segment space='253' origin='132'>"
    "<name>Switch Machines</name>"
    "<group replication='4'>"
    "<name>Servo</name>"
    "<repname>Servo 1</repname>"
    "<repname>Servo 2</repname>"
    "<repname>Servo 3</repname>"
    "<repname>Servo 4</repname>"

    "<eventid><name>Throw Command Event</name></eventid>"
    "<eventid><name>Close Command Event</name></eventid>"
    "<eventid><name>Thrown Feedback Event</name></eventid>"
    "<eventid><name>Closed Feedback Event</name></eventid>"

    "<int size='2'>"
    "<name>Thrown Position</name>"
    "<description>PWM position when thrown (0-65535)</description>"
    "<min>0</min><max>65535</max><default>16384</default>"
    "</int>"
    "<int size='2'>"
    "<name>Closed Position</name>"
    "<description>PWM position when closed (0-65535)</description>"
    "<min>0</min><max>65535</max><default>49152</default>"
    "</int>"
    "<int size='1'>"
    "<name>Throw Time</name>"
    "<description>Throw duration in tenths of a second (0=instant, 30=3.0s)</description>"
    "<min>0</min><max>255</max><default>30</default>"
    "</int>"
    "<int size='1'>"
    "<name>Hold Time</name>"
    "<description>Seconds to hold position after throw before cutting power (0=hold forever)</description>"
    "<min>0</min><max>255</max><default>2</default>"
    "</int>"
    "<int size='1'>"
    "<name>Enabled</name>"
    "<map>"
    "<relation><property>0</property><value>Disabled</value></relation>"
    "<relation><property>1</property><value>Enabled</value></relation>"
    "</map>"
    "<default>1</default>"
    "</int>"
    "<int size='1'>"
    "<name>Default State</name>"
    "<description>Position at power-on</description>"
    "<map>"
    "<relation><property>0</property><value>Thrown</value></relation>"
    "<relation><property>1</property><value>Closed</value></relation>"
    "</map>"
    "<default>0</default>"
    "</int>"
    "<int size='1'>"
    "<name>Reversed</name>"
    "<description>Swap thrown/closed direction</description>"
    "<map>"
    "<relation><property>0</property><value>Normal</value></relation>"
    "<relation><property>1</property><value>Reversed</value></relation>"
    "</map>"
    "<default>0</default>"
    "</int>"

    "<string size='7'><name>Reserved</name></string>"

    "</group>"
    "</segment>"

    "</cdi>";

const size_t cdi_xml_len = sizeof(cdi_xml); /* includes null terminator */
